spring:
  application:
    name: portfolio
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: wogus1212!
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} # 앱 비밀번호 사용
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

upload:
  path: ${UPLOAD_PATH:C:/chat_uploads/}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    # org.springframework.web: debug

